In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tensorflow.keras.layers import ZeroPadding2D,Convolution2D,MaxPooling2D,Dropout,Flatten,Dense
from tensorflow.keras.models import Sequential

In [2]:

def ConsineSim(img1,img2):
    a = np.matmul(np.transpose(img1,img2))
    b = np.sum(np.multiply(img1,img1))
    c = np.sum(np.multiply(img2,img2))
    return 1-(a/(np.sqrt(b)*np.sqrt(c)))

In [3]:
model = Sequential()
model.add(ZeroPadding2D((1,1),input_shape=(224,224,3))),
model.add(Convolution2D(64,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(64,(3,3),activation="relu")),
model.add(MaxPooling2D((2,2), strides=(2,2))),

model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(128,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(128,(3,3),activation="relu")),
model.add(MaxPooling2D((2,2), strides=(2,2))),

model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(256,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(256,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(256,(3,3),activation="relu")),
model.add(MaxPooling2D((2,2), strides=(2,2))),

model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(512,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(512,(3,3),activation="relu")),
model.add(ZeroPadding2D((1,1))),
model.add(Convolution2D(512,(3,3),activation="relu")),
model.add(MaxPooling2D((2,2), strides=(2,2))),

model.add(Convolution2D(4096,(7,7),activation="relu")),
model.add(Dropout(0.5)),
model.add(Convolution2D(4096,(1,1),activation="relu")),
model.add(Dropout(0.5)),
model.add(Convolution2D(2048,(1,1))),
model.add(Flatten()),
model.add(Dense(1,activation="softmax")),
vectorizer= tf.keras.Model(inputs=model.layers[0].input,outputs=model.layers[-2].output)
# this will give the feature vector when used for prediction for both cropped input images
# we will use cosine similarity to detect similarity in faces.

In [4]:
vectorizer

In [5]:
model.compile(optimizer=tf.keras.optimizers.Adam(),loss=tf.keras.losses.BinaryCrossentropy(),metrics=['accuracy'])

In [6]:
def load_image(x):
    byte_img = tf.io.read_file(x)
    img = tf.io.decode_jpeg(byte_img)
    return img

In [7]:
pos_data = tf.data.Dataset.list_files('cropped_faces\\face3\\*.jpg', shuffle=False)
pos_data = pos_data.map(load_image)
pos_data = pos_data.map(lambda x: x/255)
pos_data = pos_data.map(lambda x: tf.image.resize(x, (224,224)))
# adding label 1 to positive train data
pos_labels= pos_data.map(lambda x:np.array([1]))	

pos_data=tf.data.Dataset.zip(pos_data,pos_labels)
pos_data=pos_data.batch(8)

neg_data = tf.data.Dataset.list_files('cropped_faces\\face2\\*.jpg', shuffle=False)
neg_data = neg_data.map(load_image)
neg_data = neg_data.map(lambda x: x/255)
neg_data = neg_data.map(lambda x: tf.image.resize(x, (224,224)))
# adding label 0 to negative train data
neg_labels= neg_data.map(lambda x:np.array([0]))	

neg_data=tf.data.Dataset.zip(neg_data,neg_labels)
neg_data=neg_data.batch(8)

dataset = pos_data.concatenate(neg_data)
dataset.shuffle(3, reshuffle_each_iteration=True)


val_data = tf.data.Dataset.list_files('cropped_faces\\face1\\*.jpg', shuffle=False)
val_data = val_data.map(load_image)
val_data = val_data.map(lambda x: x/255)
val_data = val_data.map(lambda x: tf.image.resize(x, (224,224)))
val_labels = val_data.map(lambda x: np.array([1]))
val_data = tf.data.Dataset.zip(val_data,val_labels)
val_data=val_data.batch(8)

In [8]:
dataset

<_ConcatenateDataset element_spec=(TensorSpec(shape=(None, 224, 224, None), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.int32, name=None))>

In [9]:
model.fit(dataset,validation_split=0.2)

10/10 [==============================] - 98s 9s/step - loss: 11456.7812 - accuracy: 0.5070


In [15]:
features=dataset.as_numpy_iterator().next()
features

(array([[[[0.9278737 , 0.95371026, 0.9372549 ],
          [0.92156863, 0.95686275, 0.9372549 ],
          [0.9264644 , 0.9499938 , 0.9343075 ],
          ...,
          [0.7336897 , 0.74545443, 0.7101603 ],
          [0.73353964, 0.74530435, 0.71785337],
          [0.73333335, 0.74509805, 0.7176471 ]],
 
         [[0.92941177, 0.9529412 , 0.94509804],
          [0.92156863, 0.95686275, 0.94509804],
          [0.9254902 , 0.9490196 , 0.9411765 ],
          ...,
          [0.7320028 , 0.7437675 , 0.7084734 ],
          [0.73333335, 0.74509805, 0.7176471 ],
          [0.73333335, 0.74509805, 0.7176471 ]],
 
         [[0.92682076, 0.95035017, 0.9346639 ],
          [0.92682076, 0.95035017, 0.9346639 ],
          [0.9189776 , 0.95427173, 0.9346639 ],
          ...,
          [0.73504525, 0.74680996, 0.71151584],
          [0.73333335, 0.74509805, 0.7176471 ],
          [0.7297682 , 0.7415329 , 0.71408194]],
 
         ...,
 
         [[0.23788512, 0.24180669, 0.31239495],
          [0.22352

In [12]:
feature_vectors=vectorizer(features)

ValueError: Layer "model" expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(8, 224, 224, 3), dtype=float32, numpy=
array([[[[0.9278737 , 0.95371026, 0.9372549 ],
         [0.92156863, 0.95686275, 0.9372549 ],
         [0.9264644 , 0.9499938 , 0.9343075 ],
         ...,
         [0.7336897 , 0.74545443, 0.7101603 ],
         [0.73353964, 0.74530435, 0.71785337],
         [0.73333335, 0.74509805, 0.7176471 ]],

        [[0.92941177, 0.9529412 , 0.94509804],
         [0.92156863, 0.95686275, 0.94509804],
         [0.9254902 , 0.9490196 , 0.9411765 ],
         ...,
         [0.7320028 , 0.7437675 , 0.7084734 ],
         [0.73333335, 0.74509805, 0.7176471 ],
         [0.73333335, 0.74509805, 0.7176471 ]],

        [[0.92682076, 0.95035017, 0.9346639 ],
         [0.92682076, 0.95035017, 0.9346639 ],
         [0.9189776 , 0.95427173, 0.9346639 ],
         ...,
         [0.73504525, 0.74680996, 0.71151584],
         [0.73333335, 0.74509805, 0.7176471 ],
         [0.7297682 , 0.7415329 , 0.71408194]],

        ...,

        [[0.23788512, 0.24180669, 0.31239495],
         [0.22352941, 0.22745098, 0.29803923],
         [0.2173982 , 0.22131976, 0.29975113],
         ...,
         [0.18431373, 0.2       , 0.20392157],
         [0.1882353 , 0.19215687, 0.2       ],
         [0.19215687, 0.19607843, 0.20392157]],

        [[0.22745098, 0.23137255, 0.30980393],
         [0.22352941, 0.22745098, 0.30588236],
         [0.2170168 , 0.22093837, 0.29152662],
         ...,
         [0.19189553, 0.1958171 , 0.21150337],
         [0.19607843, 0.19215687, 0.21176471],
         [0.19607843, 0.19215687, 0.21176471]],

        [[0.22352941, 0.22745098, 0.30588236],
         [0.22352941, 0.22745098, 0.30588236],
         [0.2170168 , 0.22093837, 0.29152662],
         ...,
         [0.19418152, 0.19810309, 0.21378936],
         [0.1994361 , 0.20335767, 0.21904394],
         [0.2       , 0.20392157, 0.21960784]]],


       [[[0.90588236, 0.9411765 , 0.9372549 ],
         [0.90588236, 0.9411765 , 0.9372549 ],
         [0.90588236, 0.9411765 , 0.9372549 ],
         ...,
         [0.7019608 , 0.7137255 , 0.67058825],
         [0.7019608 , 0.7137255 , 0.67058825],
         [0.7058824 , 0.7176471 , 0.6745098 ]],

        [[0.9137255 , 0.9372549 , 0.9372549 ],
         [0.9137255 , 0.9372549 , 0.9372549 ],
         [0.9137255 , 0.9372549 , 0.9372549 ],
         ...,
         [0.69803923, 0.70980394, 0.6666667 ],
         [0.7011905 , 0.7129552 , 0.6698179 ],
         [0.702805  , 0.7145697 , 0.67143244]],

        [[0.91085434, 0.9322829 , 0.93333334],
         [0.9098039 , 0.93333334, 0.93333334],
         [0.90588236, 0.92941177, 0.92941177],
         ...,
         [0.6954482 , 0.7072129 , 0.6640757 ],
         [0.69880944, 0.71057415, 0.6674369 ],
         [0.7019608 , 0.7137255 , 0.67058825]],

        ...,

        [[0.2741534 , 0.29376125, 0.30944753],
         [0.26533613, 0.2927871 , 0.31631652],
         [0.2692577 , 0.29670867, 0.32808122],
         ...,
         [0.21827728, 0.23788512, 0.26141456],
         [0.22612041, 0.24572825, 0.26141456],
         [0.23004198, 0.24964984, 0.26533613]],

        [[0.25959378, 0.28704476, 0.31057417],
         [0.25820455, 0.28565553, 0.31702808],
         [0.25175065, 0.28704476, 0.32233888],
         ...,
         [0.19684868, 0.22429965, 0.25567222],
         [0.20861338, 0.2249186 , 0.2583559 ],
         [0.20945756, 0.2290654 , 0.25259483]],

        [[0.24236812, 0.2698191 , 0.30119166],
         [0.23711464, 0.26456565, 0.2959382 ],
         [0.2342436 , 0.26953772, 0.30483183],
         ...,
         [0.1882353 , 0.21568628, 0.24705882],
         [0.19607843, 0.21176471, 0.24705882],
         [0.19894949, 0.21540485, 0.24839167]]],


       [[[0.9529412 , 0.9607843 , 0.91764706],
         [0.9529412 , 0.9607843 , 0.91764706],
         [0.9529412 , 0.9607843 , 0.91764706],
         ...,
         [0.74650484, 0.75721914, 0.7140819 ],
         [0.7529412 , 0.7607843 , 0.70980394],
         [0.7529412 , 0.7607843 , 0.7176471 ]],

        [[0.9529412 , 0.9607843 , 0.91764706],
         [0.9529412 , 0.9607843 , 0.91764706],
         [0.9529412 , 0.9607843 , 0.91764706],
         ...,
         [0.74509805, 0.75686276, 0.7137255 ],
         [0.74978983, 0.757633  , 0.702731  ],
         [0.7482493 , 0.7560924 , 0.70511204]],

        [[0.9529412 , 0.95686275, 0.9254902 ],
         [0.9529412 , 0.95686275, 0.9254902 ],
         [0.9529412 , 0.95686275, 0.9254902 ],
         ...,
         [0.7490196 , 0.7607843 , 0.7176471 ],
         [0.7490196 , 0.75686276, 0.7019608 ],
         [0.7490196 , 0.75686276, 0.7058824 ]],

        ...,

        [[0.66141456, 0.6967087 , 0.67710084],
         [0.66799724, 0.69152665, 0.6836835 ],
         [0.6627451 , 0.6862745 , 0.6784314 ],
         ...,
         [0.6       , 0.6156863 , 0.5568628 ],
         [0.6039216 , 0.61960787, 0.56078434],
         [0.6049721 , 0.6206584 , 0.5618349 ]],

        [[0.6517506 , 0.6948879 , 0.67135847],
         [0.65190196, 0.6947366 , 0.6792016 ],
         [0.654902  , 0.6901961 , 0.6784314 ],
         ...,
         [0.59607846, 0.6039216 , 0.54901963],
         [0.6       , 0.60784316, 0.5568628 ],
         [0.60412794, 0.6119711 , 0.5609907 ]],

        [[0.6499299 , 0.69306713, 0.6695377 ],
         [0.6499299 , 0.69306713, 0.67738086],
         [0.6542079 , 0.689502  , 0.6777373 ],
         ...,
         [0.5921569 , 0.6       , 0.54901963],
         [0.5921569 , 0.6       , 0.54901963],
         [0.6       , 0.60784316, 0.5568628 ]]],


       ...,


       [[[0.9411765 , 0.9411765 , 0.9411765 ],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         ...,
         [0.77254903, 0.78039217, 0.7607843 ],
         [0.7696779 , 0.777521  , 0.7579132 ],
         [0.76862746, 0.7764706 , 0.75686276]],

        [[0.9411765 , 0.9411765 , 0.9411765 ],
         [0.9372549 , 0.9372549 , 0.9372549 ],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         ...,
         [0.770467  , 0.7783101 , 0.7587023 ],
         [0.76862746, 0.7764706 , 0.75686276],
         [0.76449955, 0.7723427 , 0.75273484]],

        [[0.9372549 , 0.9372549 , 0.9372549 ],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         ...,
         [0.77254903, 0.78039217, 0.7607843 ],
         [0.76862746, 0.7764706 , 0.75686276],
         [0.76365536, 0.7714985 , 0.75189066]],

        ...,

        [[0.2810224 , 0.3045518 , 0.35161063],
         [0.28886554, 0.3045518 , 0.35161063],
         [0.28494397, 0.29670867, 0.3555322 ],
         ...,
         [0.23049344, 0.23833658, 0.23441501],
         [0.23137255, 0.23921569, 0.23529412],
         [0.21960784, 0.23529412, 0.2334736 ]],

        [[0.2786377 , 0.29432398, 0.33746123],
         [0.2784314 , 0.29411766, 0.34117648],
         [0.27634925, 0.28811395, 0.34693748],
         ...,
         [0.23030332, 0.23814645, 0.23422489],
         [0.22884017, 0.23668331, 0.23276174],
         [0.22745098, 0.2342436 , 0.2334736 ]],

        [[0.27450982, 0.2901961 , 0.33333334],
         [0.27058825, 0.28627452, 0.33333334],
         [0.27450982, 0.28627452, 0.34509805],
         ...,
         [0.22745098, 0.23529412, 0.23137255],
         [0.22745098, 0.23529412, 0.23137255],
         [0.22745098, 0.2342436 , 0.2334736 ]]],


       [[[0.9529412 , 0.95686275, 0.93333334],
         [0.9529412 , 0.95686275, 0.9254902 ],
         [0.9529412 , 0.95686275, 0.93333334],
         ...,
         [0.7254902 , 0.7411765 , 0.68235296],
         [0.72156864, 0.74509805, 0.6901961 ],
         [0.7254902 , 0.7490196 , 0.69411767]],

        [[0.9529412 , 0.95686275, 0.93333334],
         [0.9529412 , 0.95686275, 0.9254902 ],
         [0.9529412 , 0.95686275, 0.93333334],
         ...,
         [0.7254902 , 0.7411765 , 0.6745098 ],
         [0.7254902 , 0.7411765 , 0.68235296],
         [0.73333335, 0.7490196 , 0.6901961 ]],

        [[0.9529412 , 0.95686275, 0.93333334],
         [0.9529412 , 0.95686275, 0.9254902 ],
         [0.9529412 , 0.95686275, 0.93333334],
         ...,
         [0.7294118 , 0.74509805, 0.6862745 ],
         [0.73333335, 0.7411765 , 0.6862745 ],
         [0.7336898 , 0.7415329 , 0.68663096]],

        ...,

        [[0.42086828, 0.46008396, 0.46400553],
         [0.41302514, 0.46008396, 0.46008396],
         [0.4134766 , 0.45269227, 0.45661384],
         ...,
         [0.58557415, 0.5894957 , 0.5659663 ],
         [0.59208673, 0.5960083 , 0.5724789 ],
         [0.60328513, 0.6072067 , 0.5836773 ]],

        [[0.3978991 , 0.44103634, 0.44887948],
         [0.38900554, 0.4321428 , 0.43998593],
         [0.3929271 , 0.4321428 , 0.43998593],
         ...,
         [0.5259802 , 0.52990174, 0.5102939 ],
         [0.54209805, 0.5460196 , 0.5264118 ],
         [0.56414557, 0.56806713, 0.5484593 ]],

        [[0.38718477, 0.43032202, 0.43816516],
         [0.38039216, 0.42352942, 0.43137255],
         [0.38039216, 0.41960785, 0.42745098],
         ...,
         [0.40917325, 0.41309482, 0.39348698],
         [0.43711442, 0.441036  , 0.42142814],
         [0.47135824, 0.4752798 , 0.45567197]]],


       [[[0.9411765 , 0.9411765 , 0.9411765 ],
         [0.9422269 , 0.9422269 , 0.9422269 ],
         [0.94509804, 0.94509804, 0.94509804],
         ...,
         [0.7790616 , 0.77514005, 0.7594538 ],
         [0.77254903, 0.7764706 , 0.7529412 ],
         [0.76862746, 0.77254903, 0.7490196 ]],

        [[0.94040614, 0.94040614, 0.94040614],
         [0.9411765 , 0.9411765 , 0.9411765 ],
         [0.94509804, 0.94509804, 0.94509804],
         ...,
         [0.7790616 , 0.77514005, 0.7594538 ],
         [0.7693977 , 0.77331924, 0.74978983],
         [0.7647059 , 0.76862746, 0.74509805]],

        [[0.9372549 , 0.9372549 , 0.9372549 ],
         [0.94509804, 0.94509804, 0.94509804],
         [0.94509804, 0.94509804, 0.94509804],
         ...,
         [0.78039217, 0.7764706 , 0.7607843 ],
         [0.7693977 , 0.77331924, 0.7434872 ],
         [0.76757693, 0.7714985 , 0.74012595]],

        ...,

        [[0.2741534 , 0.29768282, 0.29768282],
         [0.27317926, 0.29670867, 0.29670867],
         [0.27450982, 0.29803923, 0.2901961 ],
         ...,
         [0.21176471, 0.21960784, 0.21568628],
         [0.21568628, 0.21568628, 0.20784314],
         [0.21827728, 0.21827728, 0.21043414]],

        [[0.2734594 , 0.2901961 , 0.3019608 ],
         [0.27450982, 0.2901961 , 0.29411766],
         [0.27109715, 0.29462656, 0.29462656],
         ...,
         [0.21227361, 0.21227361, 0.20443048],
         [0.21568628, 0.21568628, 0.21568628],
         [0.21876366, 0.21876366, 0.21876366]],

        [[0.26666668, 0.28235295, 0.29411766],
         [0.27058825, 0.28627452, 0.2901961 ],
         [0.26666668, 0.28235295, 0.28837556],
         ...,
         [0.20784314, 0.20784314, 0.20784314],
         [0.21176471, 0.21176471, 0.21176471],
         [0.21568628, 0.21568628, 0.21568628]]]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>]

In [19]:
def verify(img1,img2):
    vec1 = model.predict(img1)
    vec2 = model.predict(img2)
    sim = ConsineSim(vec1,vec2)
    threshold = 0.4
    
    f = plt.figure()
    f.add_subplot(1,2,1)
    plt.imshow(vec1)
    plt.xticks([])
    plt.yticks([])
    f.add_subplot(1,2,2)
    plt.imshow(vec2)
    plt.xticks([])
    plt.yticks([])
    plt.show(block=True)
    
    print("Cosine Similarity: ",sim) 
    if sim<threshold:
        print("They are same person")
    else:
        print("They are not same person") 

In [22]:
img1 = cv2.imread("./IMG_20230427_111749_copy.jpg")
img1 = cv2.resize(img1,(224,224))
img1 = tf.expand_dims(img1,0)

img2 = cv2.imread("./IMG_20230427_111749_copy.jpg")
img2 = cv2.resize(img2,(224,224))
img2 = tf.expand_dims(img2,0)

In [25]:
img1

TensorShape([1, 224, 224, 3])

In [24]:
ConsineSim(img1,img2)

TypeError: only integer scalar arrays can be converted to a scalar index